### ISSUE TITLE
App crashes on launch if no Internet connection

### ISSUE THREAD

**Issue by rcmaehl** [CyanLabs/Syn3Updater#189] opened 2023-01-03 02:51 UTC
The app does not seem to be able to launch if there is no Internet connection, or the Internet connection is too slow such as a mobile hotspot.

**Comment by Fma965** [comment] 2023-01-03 02:52
Not a bug, the app requires internet connectivity to pull data from cyanlabs for lists of packages and releases etc.

**Comment by Fma965** [comment] 2023-05-07 13:41
You need internet to use this app, so no reason to spend time resolving this.

**Closed by Fma965** 2023-05-07 13:41 UTC
